name: "Bug Report"
description: Report an issue to help improve La Voix Locale
title: "[BUG] - "
labels: ["bug 🪲"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the application is affected?
      placeholder: "e.g. Authentication, Language Tools, etc."
    validations:
      required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Type of Bug
      multiple: true
      options:
        - Frontend/UI Issue
        - Backend/Server Issue
        - Authentication Problem
        - Performance Issue
        - Language Processing Error
        - Data Loss/Corruption
        - Security Concern
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - Browser: [e.g. Chrome 121]
        - OS: [e.g. Windows 11]
        - Screen Size: [e.g. 1920x1080]
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
