name: "Feature Request"
description: "Suggest an idea for this project"
title: "[FEATURE] - "
labels: ["feature ⭐"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: Give your feature a clear and concise name
      placeholder: "e.g., Multi-language Support"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Describe the feature you'd like to see implemented
      placeholder: A clear and detailed description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this feature to be considered complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Any other solutions or features that could achieve the same goal
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Any additional information that might be helpful
    validations:
      required: false
